name: atbash-cipher
version: 1.2.0.7

dependencies:
  - base

library:
  exposed-modules: Atbash
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - text       # List here the packages you

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - atbash-cipher
      - hspec
