name: wordy
version: 1.5.0.8

dependencies:
  - base

library:
  exposed-modules: WordProblem
  haskell.ghcMod.executablePath: "stack"
  source-dirs: src
  default-extensions: OverloadedStrings
  dependencies:
  - megaparsec
  - text
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - wordy
      - hspec
