name: wordy
version: 1.5.0.8

dependencies:
  - base

library:
  exposed-modules: WordProblem
  source-dirs: src
  ghc-options: -Wall
  default-extensions: OverloadedStrings
  dependencies:
  - text     
  - parser-combinators
  - megaparsec      

tests:
  test:
    main: Tests.hs
    source-dirs: test
    default-extensions: OverloadedStrings
    dependencies:
      - wordy
      - hspec
